### ISSUE TITLE
symfony domains -> loco tags

### ISSUE THREAD

**Issue by hoffereka** [Happyr/TranslationBundle#47]
Hi,
we have a relatively simple symfony 2.7 app with three domains: messages, validators and DataGrid.
When I push up everything to loco, then I sync back, in every translation file appears all domains translations, mixed up. My config is:
```
happyr_translation:
    httplug_client: 'httplug.client'
    httplug_message_factory: 'httplug.message_factory'
    file_extension: 'xlf' # could be  'json', 'mo', 'php', 'po', 'yaml' and many more
    locales: [hu, en]
    domains: ['messages', 'validators', 'DataGridBundle']
    projects:
        managedoc:
            api_key: 'deadbeef'
    translation_service: 'loco'
    target_dir: '%kernel.root_dir%/../src/Agendie/ReservationBundle/Resources/translations'
    auto_add_assets: false
    allow_edit: true
```
thanks in advance for Your response!
